-- ============================================================
-- Herbalife Lookup Management System
-- Oracle Database schema (DDL)
-- ============================================================

-- ------------------------------------------------------------
-- 1. REFERENCE / SUPPORTING TABLES
-- ------------------------------------------------------------

CREATE TABLE MODULES (
    MODULE_CODE       VARCHAR2(30)   NOT NULL,
    MODULE_NAME       VARCHAR2(100)  NOT NULL,
    DESCRIPTION       VARCHAR2(400),
    ENABLED_FLAG      CHAR(1)        DEFAULT 'Y' NOT NULL,
    CREATED_BY        VARCHAR2(100)  NOT NULL,
    CREATED_DATE      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_UPDATED_BY   VARCHAR2(100),
    LAST_UPDATED_DATE TIMESTAMP,
    CONSTRAINT PK_MODULES PRIMARY KEY (MODULE_CODE),
    CONSTRAINT CK_MODULES_ENABLED CHECK (ENABLED_FLAG IN ('Y','N'))
);

CREATE TABLE LANGUAGES (
    LANGUAGE_CODE  VARCHAR2(10)  NOT NULL,
    LANGUAGE_NAME  VARCHAR2(60)  NOT NULL,
    ENABLED_FLAG   CHAR(1)       DEFAULT 'Y' NOT NULL,
    IS_DEFAULT     CHAR(1)       DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_LANGUAGES PRIMARY KEY (LANGUAGE_CODE),
    CONSTRAINT CK_LANGUAGES_ENABLED CHECK (ENABLED_FLAG IN ('Y','N')),
    CONSTRAINT CK_LANGUAGES_DEFAULT CHECK (IS_DEFAULT IN ('Y','N'))
);

CREATE TABLE USERS (
    USER_ID      RAW(16)       DEFAULT SYS_GUID() NOT NULL,
    USERNAME     VARCHAR2(100) NOT NULL,
    EMAIL        VARCHAR2(200) NOT NULL,
    FULL_NAME    VARCHAR2(150) NOT NULL,
    INITIALS     VARCHAR2(5),
    ACTIVE_FLAG  CHAR(1)       DEFAULT 'Y' NOT NULL,
    CREATED_DATE TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USERS_ACTIVE CHECK (ACTIVE_FLAG IN ('Y','N'))
);

CREATE TABLE ROLES (
    ROLE_CODE    VARCHAR2(50)  NOT NULL,
    ROLE_NAME    VARCHAR2(150) NOT NULL,
    DESCRIPTION  VARCHAR2(400),
    ENABLED_FLAG CHAR(1)       DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_ROLES PRIMARY KEY (ROLE_CODE),
    CONSTRAINT CK_ROLES_ENABLED CHECK (ENABLED_FLAG IN ('Y','N'))
);

-- ------------------------------------------------------------
-- 2. LOOKUP TYPES & VALUES
-- ------------------------------------------------------------

CREATE TABLE LOOKUP_TYPES (
    LOOKUP_TYPE_CODE  VARCHAR2(60)  NOT NULL,
    MEANING           VARCHAR2(200) NOT NULL,
    DESCRIPTION       VARCHAR2(500),
    MODULE_CODE       VARCHAR2(30)  NOT NULL,
    ENABLED_FLAG      CHAR(1)       DEFAULT 'Y' NOT NULL,
    CREATED_BY        VARCHAR2(100) NOT NULL,
    CREATED_DATE      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_UPDATED_BY   VARCHAR2(100),
    LAST_UPDATED_DATE TIMESTAMP,
    CONSTRAINT PK_LOOKUP_TYPES PRIMARY KEY (LOOKUP_TYPE_CODE),
    CONSTRAINT FK_LKPTYPE_MODULE FOREIGN KEY (MODULE_CODE) REFERENCES MODULES(MODULE_CODE),
    CONSTRAINT CK_LKPTYPE_ENABLED CHECK (ENABLED_FLAG IN ('Y','N'))
);

CREATE TABLE LOOKUP_VALUES (
    LOOKUP_VALUE_ID   NUMBER        GENERATED ALWAYS AS IDENTITY NOT NULL,
    LOOKUP_TYPE_CODE  VARCHAR2(60)  NOT NULL,
    VALUE_CODE        VARCHAR2(60)  NOT NULL,
    MEANING           VARCHAR2(200) NOT NULL,
    DESCRIPTION       VARCHAR2(500),
    ENABLED_FLAG      CHAR(1)       DEFAULT 'Y' NOT NULL,
    START_DATE        DATE          DEFAULT SYSDATE NOT NULL,
    END_DATE          DATE,
    DISPLAY_SEQ       NUMBER(10)    DEFAULT 10,
    CREATED_BY        VARCHAR2(100) NOT NULL,
    CREATED_DATE      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_UPDATED_BY   VARCHAR2(100),
    LAST_UPDATED_DATE TIMESTAMP,
    CONSTRAINT PK_LOOKUP_VALUES PRIMARY KEY (LOOKUP_VALUE_ID),
    CONSTRAINT FK_LKPVAL_TYPE FOREIGN KEY (LOOKUP_TYPE_CODE)
        REFERENCES LOOKUP_TYPES(LOOKUP_TYPE_CODE) ON DELETE CASCADE,
    CONSTRAINT UQ_LKPVAL_CODE UNIQUE (LOOKUP_TYPE_CODE, VALUE_CODE),
    CONSTRAINT CK_LKPVAL_ENABLED CHECK (ENABLED_FLAG IN ('Y','N')),
    CONSTRAINT CK_LKPVAL_DATES CHECK (END_DATE IS NULL OR END_DATE >= START_DATE)
);

CREATE TABLE LOOKUP_VALUE_TRANSLATIONS (
    TRANSLATION_ID     NUMBER        GENERATED ALWAYS AS IDENTITY NOT NULL,
    LOOKUP_VALUE_ID    NUMBER        NOT NULL,
    LANGUAGE_CODE      VARCHAR2(10)  NOT NULL,
    TRANSLATED_MEANING VARCHAR2(200) NOT NULL,
    STATUS             VARCHAR2(20)  DEFAULT 'draft' NOT NULL,
    TRANSLATED_BY      VARCHAR2(100),
    LAST_MODIFIED      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_LKPVAL_TRANS PRIMARY KEY (TRANSLATION_ID),
    CONSTRAINT FK_LKPVALTRANS_VAL FOREIGN KEY (LOOKUP_VALUE_ID)
        REFERENCES LOOKUP_VALUES(LOOKUP_VALUE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LKPVALTRANS_LANG FOREIGN KEY (LANGUAGE_CODE) REFERENCES LANGUAGES(LANGUAGE_CODE),
    CONSTRAINT UQ_LKPVAL_TRANS UNIQUE (LOOKUP_VALUE_ID, LANGUAGE_CODE),
    CONSTRAINT CK_LKPVALTRANS_STATUS CHECK (STATUS IN ('active','needs-review','draft'))
);

-- ------------------------------------------------------------
-- 3. VALUE SETS & VALUES (hierarchy-capable, e.g. DEPT_HIERARCHY)
-- ------------------------------------------------------------

CREATE TABLE VALUE_SETS (
    VALUE_SET_CODE    VARCHAR2(60)  NOT NULL,
    VALUE_SET_NAME    VARCHAR2(200) NOT NULL,
    MODULE_CODE       VARCHAR2(30)  NOT NULL,
    VALIDATION_TYPE   VARCHAR2(30)  NOT NULL,
    FORMAT_TYPE       VARCHAR2(30),
    MAX_LENGTH        NUMBER(6),
    ENABLED_FLAG      CHAR(1)       DEFAULT 'Y' NOT NULL,
    CREATED_BY        VARCHAR2(100) NOT NULL,
    CREATED_DATE      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_UPDATED_BY   VARCHAR2(100),
    LAST_UPDATED_DATE TIMESTAMP,
    CONSTRAINT PK_VALUE_SETS PRIMARY KEY (VALUE_SET_CODE),
    CONSTRAINT FK_VS_MODULE FOREIGN KEY (MODULE_CODE) REFERENCES MODULES(MODULE_CODE),
    CONSTRAINT CK_VS_ENABLED CHECK (ENABLED_FLAG IN ('Y','N'))
);

CREATE TABLE VALUE_SET_VALUES (
    VALUE_ID          NUMBER        GENERATED ALWAYS AS IDENTITY NOT NULL,
    VALUE_SET_CODE    VARCHAR2(60)  NOT NULL,
    VALUE_CODE        VARCHAR2(60)  NOT NULL,
    VALUE_NAME        VARCHAR2(200) NOT NULL,
    PARENT_VALUE_ID   NUMBER,
    DISPLAY_SEQ       NUMBER(10)    DEFAULT 10,
    ENABLED_FLAG      CHAR(1)       DEFAULT 'Y' NOT NULL,
    CREATED_BY        VARCHAR2(100) NOT NULL,
    CREATED_DATE      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_UPDATED_BY   VARCHAR2(100),
    LAST_UPDATED_DATE TIMESTAMP,
    CONSTRAINT PK_VS_VALUES PRIMARY KEY (VALUE_ID),
    CONSTRAINT FK_VSVAL_SET FOREIGN KEY (VALUE_SET_CODE)
        REFERENCES VALUE_SETS(VALUE_SET_CODE) ON DELETE CASCADE,
    CONSTRAINT FK_VSVAL_PARENT FOREIGN KEY (PARENT_VALUE_ID) REFERENCES VALUE_SET_VALUES(VALUE_ID),
    CONSTRAINT UQ_VSVAL_CODE UNIQUE (VALUE_SET_CODE, VALUE_CODE),
    CONSTRAINT CK_VSVAL_ENABLED CHECK (ENABLED_FLAG IN ('Y','N'))
);

CREATE TABLE VALUE_SET_VALUE_TRANSLATIONS (
    TRANSLATION_ID   NUMBER        GENERATED ALWAYS AS IDENTITY NOT NULL,
    VALUE_ID         NUMBER        NOT NULL,
    LANGUAGE_CODE    VARCHAR2(10)  NOT NULL,
    TRANSLATED_VALUE VARCHAR2(200) NOT NULL,
    STATUS           VARCHAR2(20)  DEFAULT 'draft' NOT NULL,
    TRANSLATED_BY    VARCHAR2(100),
    LAST_MODIFIED    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_VS_TRANS PRIMARY KEY (TRANSLATION_ID),
    CONSTRAINT FK_VSTRANS_VAL FOREIGN KEY (VALUE_ID)
        REFERENCES VALUE_SET_VALUES(VALUE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_VSTRANS_LANG FOREIGN KEY (LANGUAGE_CODE) REFERENCES LANGUAGES(LANGUAGE_CODE),
    CONSTRAINT UQ_VS_TRANS UNIQUE (VALUE_ID, LANGUAGE_CODE),
    CONSTRAINT CK_VSTRANS_STATUS CHECK (STATUS IN ('active','needs-review','draft'))
);

-- ------------------------------------------------------------
-- 4. ROLES, PERMISSIONS & ASSIGNMENTS (multi-module scope)
-- ------------------------------------------------------------

CREATE TABLE ROLE_PERMISSIONS (
    PERMISSION_ID  NUMBER        GENERATED ALWAYS AS IDENTITY NOT NULL,
    ROLE_CODE      VARCHAR2(50)  NOT NULL,
    MODULE_CODE    VARCHAR2(30)  NOT NULL,
    CAN_READ       CHAR(1)       DEFAULT 'Y' NOT NULL,
    CAN_CREATE     CHAR(1)       DEFAULT 'N' NOT NULL,
    CAN_UPDATE     CHAR(1)       DEFAULT 'N' NOT NULL,
    CAN_DELETE     CHAR(1)       DEFAULT 'N' NOT NULL,
    CONDITION_NOTE VARCHAR2(500),
    CONSTRAINT PK_ROLE_PERMISSIONS PRIMARY KEY (PERMISSION_ID),
    CONSTRAINT FK_ROLEPERM_ROLE FOREIGN KEY (ROLE_CODE) REFERENCES ROLES(ROLE_CODE),
    CONSTRAINT FK_ROLEPERM_MODULE FOREIGN KEY (MODULE_CODE) REFERENCES MODULES(MODULE_CODE),
    CONSTRAINT UQ_ROLEPERM UNIQUE (ROLE_CODE, MODULE_CODE),
    CONSTRAINT CK_ROLEPERM_READ CHECK (CAN_READ IN ('Y','N')),
    CONSTRAINT CK_ROLEPERM_CREATE CHECK (CAN_CREATE IN ('Y','N')),
    CONSTRAINT CK_ROLEPERM_UPDATE CHECK (CAN_UPDATE IN ('Y','N')),
    CONSTRAINT CK_ROLEPERM_DELETE CHECK (CAN_DELETE IN ('Y','N'))
);

CREATE TABLE USER_ROLE_ASSIGNMENTS (
    ASSIGNMENT_ID RAW(16)      DEFAULT SYS_GUID() NOT NULL,
    USER_ID       RAW(16)      NOT NULL,
    ROLE_CODE     VARCHAR2(50) NOT NULL,
    ASSIGNED_BY   RAW(16)      NOT NULL,
    ASSIGNED_DATE TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    STATUS        VARCHAR2(20) DEFAULT 'active' NOT NULL,
    CONSTRAINT PK_USER_ROLE_ASSIGN PRIMARY KEY (ASSIGNMENT_ID),
    CONSTRAINT FK_URA_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_URA_ROLE FOREIGN KEY (ROLE_CODE) REFERENCES ROLES(ROLE_CODE),
    CONSTRAINT FK_URA_ASSIGNEDBY FOREIGN KEY (ASSIGNED_BY) REFERENCES USERS(USER_ID),
    CONSTRAINT CK_URA_STATUS CHECK (STATUS IN ('active','inactive'))
);

-- Junction table: one assignment may be scoped to many functional modules.
-- Backs the multi-select "Scope / Functional Module" field in the Assign
-- Security Role dialog and the comma-separated Scope column in the grid.
CREATE TABLE USER_ROLE_ASSIGNMENT_SCOPES (
    ASSIGNMENT_ID RAW(16)      NOT NULL,
    MODULE_CODE   VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_URA_SCOPES PRIMARY KEY (ASSIGNMENT_ID, MODULE_CODE),
    CONSTRAINT FK_URASCOPE_ASSIGN FOREIGN KEY (ASSIGNMENT_ID)
        REFERENCES USER_ROLE_ASSIGNMENTS(ASSIGNMENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_URASCOPE_MODULE FOREIGN KEY (MODULE_CODE) REFERENCES MODULES(MODULE_CODE)
);

-- ------------------------------------------------------------
-- 5. AUDIT LOG
-- ------------------------------------------------------------

CREATE TABLE AUDIT_LOG (
    AUDIT_ID        NUMBER         GENERATED ALWAYS AS IDENTITY NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    USER_ID         RAW(16)        NOT NULL,
    ROLE_CODE       VARCHAR2(50),
    ACTION          VARCHAR2(20)   NOT NULL,
    ENTITY_TYPE     VARCHAR2(30)   NOT NULL,
    ENTITY_KEY      VARCHAR2(200),
    SUMMARY         VARCHAR2(1000) NOT NULL,
    IP_ADDRESS      VARCHAR2(45),
    STATUS          VARCHAR2(20)   DEFAULT 'success' NOT NULL,
    BEFORE_VALUE    CLOB,
    AFTER_VALUE     CLOB,
    SESSION_ID      VARCHAR2(100),
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (AUDIT_ID),
    CONSTRAINT FK_AUDIT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT CK_AUDIT_ACTION CHECK (ACTION IN ('CREATE','UPDATE','DELETE','VIEW','LOGIN','EXPORT')),
    CONSTRAINT CK_AUDIT_ENTITY CHECK (ENTITY_TYPE IN ('lookup-type','value-set','user-roles','system','security')),
    CONSTRAINT CK_AUDIT_STATUS CHECK (STATUS IN ('success','failed','warning'))
) LOB (BEFORE_VALUE, AFTER_VALUE) STORE AS SECUREFILE;

-- ------------------------------------------------------------
-- 6. INDEXES
-- ------------------------------------------------------------

CREATE INDEX IX_LKPVAL_TYPE     ON LOOKUP_VALUES(LOOKUP_TYPE_CODE);
CREATE INDEX IX_LKPVAL_ENABLED  ON LOOKUP_VALUES(ENABLED_FLAG);
CREATE INDEX IX_VSVAL_SET       ON VALUE_SET_VALUES(VALUE_SET_CODE);
CREATE INDEX IX_VSVAL_PARENT    ON VALUE_SET_VALUES(PARENT_VALUE_ID);
CREATE INDEX IX_URA_USER        ON USER_ROLE_ASSIGNMENTS(USER_ID);
CREATE INDEX IX_URA_ROLE        ON USER_ROLE_ASSIGNMENTS(ROLE_CODE);
CREATE INDEX IX_URA_STATUS      ON USER_ROLE_ASSIGNMENTS(STATUS);
CREATE INDEX IX_AUDIT_USER      ON AUDIT_LOG(USER_ID);
CREATE INDEX IX_AUDIT_TIMESTAMP ON AUDIT_LOG(EVENT_TIMESTAMP);
CREATE INDEX IX_AUDIT_ENTITY    ON AUDIT_LOG(ENTITY_TYPE, ENTITY_KEY);
CREATE INDEX IX_LKPTRANS_LANG   ON LOOKUP_VALUE_TRANSLATIONS(LANGUAGE_CODE);
CREATE INDEX IX_VSTRANS_LANG    ON VALUE_SET_VALUE_TRANSLATIONS(LANGUAGE_CODE);
