-- ============================================================
-- Herbalife Lookup Management System
-- Seed data matching the mock data used by the Angular UI
-- Run after schema.sql
-- ============================================================

-- ---------- Modules ----------
INSERT INTO MODULES (MODULE_CODE, MODULE_NAME, DESCRIPTION, CREATED_BY)
VALUES ('GLOBAL', 'Global (All Modules)', 'Applies across every functional module', 'SEED');
INSERT INTO MODULES (MODULE_CODE, MODULE_NAME, DESCRIPTION, CREATED_BY)
VALUES ('HR', 'Human Resources', 'Human Resources module', 'SEED');
INSERT INTO MODULES (MODULE_CODE, MODULE_NAME, DESCRIPTION, CREATED_BY)
VALUES ('FIN', 'Financials', 'Financials module', 'SEED');
INSERT INTO MODULES (MODULE_CODE, MODULE_NAME, DESCRIPTION, CREATED_BY)
VALUES ('OPS', 'Operations', 'Operations module', 'SEED');
INSERT INTO MODULES (MODULE_CODE, MODULE_NAME, DESCRIPTION, CREATED_BY)
VALUES ('SND', 'Sales & Distribution', 'Sales and Distribution module', 'SEED');

-- ---------- Languages ----------
INSERT INTO LANGUAGES (LANGUAGE_CODE, LANGUAGE_NAME, IS_DEFAULT) VALUES ('en-US', 'English (US)', 'Y');
INSERT INTO LANGUAGES (LANGUAGE_CODE, LANGUAGE_NAME, IS_DEFAULT) VALUES ('es-ES', 'Spanish (Spain)', 'N');
INSERT INTO LANGUAGES (LANGUAGE_CODE, LANGUAGE_NAME, IS_DEFAULT) VALUES ('fr-FR', 'French (France)', 'N');
INSERT INTO LANGUAGES (LANGUAGE_CODE, LANGUAGE_NAME, IS_DEFAULT) VALUES ('de-DE', 'German (Germany)', 'N');
INSERT INTO LANGUAGES (LANGUAGE_CODE, LANGUAGE_NAME, IS_DEFAULT) VALUES ('zh-CN', 'Chinese (Simplified)', 'N');
INSERT INTO LANGUAGES (LANGUAGE_CODE, LANGUAGE_NAME, IS_DEFAULT) VALUES ('pt-BR', 'Portuguese (Brazil)', 'N');

-- ---------- Roles ----------
INSERT INTO ROLES (ROLE_CODE, ROLE_NAME, DESCRIPTION)
VALUES ('SYS_ADMIN', 'System Administrator', 'Full administrative access to all modules and configuration');
INSERT INTO ROLES (ROLE_CODE, ROLE_NAME, DESCRIPTION)
VALUES ('HR_ADMIN', 'HR Administrator', 'Manages Human Resources lookups and value sets');
INSERT INTO ROLES (ROLE_CODE, ROLE_NAME, DESCRIPTION)
VALUES ('FIN_ADMIN', 'Finance Administrator', 'Manages Financials lookups and value sets');
INSERT INTO ROLES (ROLE_CODE, ROLE_NAME, DESCRIPTION)
VALUES ('TRANSLATOR', 'Translator', 'Maintains translations for lookup and value set data');
INSERT INTO ROLES (ROLE_CODE, ROLE_NAME, DESCRIPTION)
VALUES ('VIEWER', 'Viewer', 'Read-only access to lookups, value sets and translations');

-- ---------- Role permissions ----------
INSERT INTO ROLE_PERMISSIONS (ROLE_CODE, MODULE_CODE, CAN_READ, CAN_CREATE, CAN_UPDATE, CAN_DELETE)
VALUES ('SYS_ADMIN', 'GLOBAL', 'Y', 'Y', 'Y', 'Y');
INSERT INTO ROLE_PERMISSIONS (ROLE_CODE, MODULE_CODE, CAN_READ, CAN_CREATE, CAN_UPDATE, CAN_DELETE)
VALUES ('HR_ADMIN', 'HR', 'Y', 'Y', 'Y', 'N');
INSERT INTO ROLE_PERMISSIONS (ROLE_CODE, MODULE_CODE, CAN_READ, CAN_CREATE, CAN_UPDATE, CAN_DELETE)
VALUES ('FIN_ADMIN', 'FIN', 'Y', 'Y', 'Y', 'N');
INSERT INTO ROLE_PERMISSIONS (ROLE_CODE, MODULE_CODE, CAN_READ, CAN_CREATE, CAN_UPDATE, CAN_DELETE)
VALUES ('TRANSLATOR', 'GLOBAL', 'Y', 'N', 'Y', 'N');
INSERT INTO ROLE_PERMISSIONS (ROLE_CODE, MODULE_CODE, CAN_READ, CAN_CREATE, CAN_UPDATE, CAN_DELETE)
VALUES ('VIEWER', 'GLOBAL', 'Y', 'N', 'N', 'N');

-- ---------- Users ----------
INSERT INTO USERS (USERNAME, EMAIL, FULL_NAME, INITIALS)
VALUES ('sarah.chen', 'sarah.chen@herbalife.com', 'Sarah Chen', 'SC');
INSERT INTO USERS (USERNAME, EMAIL, FULL_NAME, INITIALS)
VALUES ('michael.rodriguez', 'michael.rodriguez@herbalife.com', 'Michael Rodriguez', 'MR');
INSERT INTO USERS (USERNAME, EMAIL, FULL_NAME, INITIALS)
VALUES ('emily.watson', 'emily.watson@herbalife.com', 'Emily Watson', 'EW');
INSERT INTO USERS (USERNAME, EMAIL, FULL_NAME, INITIALS)
VALUES ('david.kim', 'david.kim@herbalife.com', 'David Kim', 'DK');

-- ---------- Role assignments (multi-module scope) ----------
DECLARE
    l_admin_id      USERS.USER_ID%TYPE;
    l_assignment_id USER_ROLE_ASSIGNMENTS.ASSIGNMENT_ID%TYPE;

    PROCEDURE assign_role (
        p_username    IN VARCHAR2,
        p_role_code   IN VARCHAR2,
        p_modules     IN SYS.ODCIVARCHAR2LIST
    ) IS
        l_user_id USERS.USER_ID%TYPE;
        l_id      USER_ROLE_ASSIGNMENTS.ASSIGNMENT_ID%TYPE;
    BEGIN
        SELECT USER_ID INTO l_user_id FROM USERS WHERE USERNAME = p_username;

        INSERT INTO USER_ROLE_ASSIGNMENTS (USER_ID, ROLE_CODE, ASSIGNED_BY)
        VALUES (l_user_id, p_role_code, l_admin_id)
        RETURNING ASSIGNMENT_ID INTO l_id;

        FOR i IN 1 .. p_modules.COUNT LOOP
            INSERT INTO USER_ROLE_ASSIGNMENT_SCOPES (ASSIGNMENT_ID, MODULE_CODE)
            VALUES (l_id, p_modules(i));
        END LOOP;
    END assign_role;
BEGIN
    SELECT USER_ID INTO l_admin_id FROM USERS WHERE USERNAME = 'sarah.chen';

    assign_role('sarah.chen',        'SYS_ADMIN',  SYS.ODCIVARCHAR2LIST('GLOBAL'));
    assign_role('michael.rodriguez', 'HR_ADMIN',   SYS.ODCIVARCHAR2LIST('HR', 'OPS'));
    assign_role('emily.watson',      'FIN_ADMIN',  SYS.ODCIVARCHAR2LIST('FIN', 'SND'));
    assign_role('david.kim',         'TRANSLATOR', SYS.ODCIVARCHAR2LIST('GLOBAL'));
END;
/

-- ---------- Lookup types & values ----------
INSERT INTO LOOKUP_TYPES (LOOKUP_TYPE_CODE, MEANING, DESCRIPTION, MODULE_CODE, CREATED_BY)
VALUES ('EMP_STATUS', 'Employee Status', 'Employment status codes', 'HR', 'SEED');
INSERT INTO LOOKUP_TYPES (LOOKUP_TYPE_CODE, MEANING, DESCRIPTION, MODULE_CODE, CREATED_BY)
VALUES ('PAY_TERMS', 'Payment Terms', 'Supplier and customer payment terms', 'FIN', 'SEED');
INSERT INTO LOOKUP_TYPES (LOOKUP_TYPE_CODE, MEANING, DESCRIPTION, MODULE_CODE, CREATED_BY)
VALUES ('ORDER_TYPE', 'Order Type', 'Sales order classification', 'SND', 'SEED');

INSERT INTO LOOKUP_VALUES (LOOKUP_TYPE_CODE, VALUE_CODE, MEANING, DISPLAY_SEQ, CREATED_BY)
VALUES ('EMP_STATUS', 'ACTIVE', 'Active', 10, 'SEED');
INSERT INTO LOOKUP_VALUES (LOOKUP_TYPE_CODE, VALUE_CODE, MEANING, DISPLAY_SEQ, CREATED_BY)
VALUES ('EMP_STATUS', 'LEAVE', 'On Leave', 20, 'SEED');
INSERT INTO LOOKUP_VALUES (LOOKUP_TYPE_CODE, VALUE_CODE, MEANING, DISPLAY_SEQ, CREATED_BY)
VALUES ('EMP_STATUS', 'TERMINATED', 'Terminated', 30, 'SEED');
INSERT INTO LOOKUP_VALUES (LOOKUP_TYPE_CODE, VALUE_CODE, MEANING, DISPLAY_SEQ, CREATED_BY)
VALUES ('PAY_TERMS', 'NET30', 'Net 30 Days', 10, 'SEED');
INSERT INTO LOOKUP_VALUES (LOOKUP_TYPE_CODE, VALUE_CODE, MEANING, DISPLAY_SEQ, CREATED_BY)
VALUES ('PAY_TERMS', 'NET60', 'Net 60 Days', 20, 'SEED');
INSERT INTO LOOKUP_VALUES (LOOKUP_TYPE_CODE, VALUE_CODE, MEANING, DISPLAY_SEQ, CREATED_BY)
VALUES ('ORDER_TYPE', 'STANDARD', 'Standard Order', 10, 'SEED');
INSERT INTO LOOKUP_VALUES (LOOKUP_TYPE_CODE, VALUE_CODE, MEANING, DISPLAY_SEQ, CREATED_BY)
VALUES ('ORDER_TYPE', 'RETURN', 'Return Order', 20, 'SEED');

INSERT INTO LOOKUP_VALUE_TRANSLATIONS (LOOKUP_VALUE_ID, LANGUAGE_CODE, TRANSLATED_MEANING, STATUS, TRANSLATED_BY)
SELECT LOOKUP_VALUE_ID, 'es-ES', 'Activo', 'active', 'david.kim'
FROM LOOKUP_VALUES WHERE LOOKUP_TYPE_CODE = 'EMP_STATUS' AND VALUE_CODE = 'ACTIVE';
INSERT INTO LOOKUP_VALUE_TRANSLATIONS (LOOKUP_VALUE_ID, LANGUAGE_CODE, TRANSLATED_MEANING, STATUS, TRANSLATED_BY)
SELECT LOOKUP_VALUE_ID, 'fr-FR', 'Actif', 'needs-review', 'david.kim'
FROM LOOKUP_VALUES WHERE LOOKUP_TYPE_CODE = 'EMP_STATUS' AND VALUE_CODE = 'ACTIVE';

-- ---------- Value sets ----------
INSERT INTO VALUE_SETS (VALUE_SET_CODE, VALUE_SET_NAME, MODULE_CODE, VALIDATION_TYPE, FORMAT_TYPE, MAX_LENGTH, CREATED_BY)
VALUES ('DEPT_HIERARCHY', 'Department Hierarchy', 'HR', 'Table', 'Char', 30, 'SEED');
INSERT INTO VALUE_SETS (VALUE_SET_CODE, VALUE_SET_NAME, MODULE_CODE, VALIDATION_TYPE, FORMAT_TYPE, MAX_LENGTH, CREATED_BY)
VALUES ('COST_CENTER', 'Cost Center', 'FIN', 'Independent', 'Char', 10, 'SEED');

DECLARE
    l_corp NUMBER;
    l_ops  NUMBER;
BEGIN
    INSERT INTO VALUE_SET_VALUES (VALUE_SET_CODE, VALUE_CODE, VALUE_NAME, DISPLAY_SEQ, CREATED_BY)
    VALUES ('DEPT_HIERARCHY', 'CORP', 'Corporate', 10, 'SEED')
    RETURNING VALUE_ID INTO l_corp;

    INSERT INTO VALUE_SET_VALUES (VALUE_SET_CODE, VALUE_CODE, VALUE_NAME, PARENT_VALUE_ID, DISPLAY_SEQ, CREATED_BY)
    VALUES ('DEPT_HIERARCHY', 'OPS', 'Operations', l_corp, 20, 'SEED')
    RETURNING VALUE_ID INTO l_ops;

    INSERT INTO VALUE_SET_VALUES (VALUE_SET_CODE, VALUE_CODE, VALUE_NAME, PARENT_VALUE_ID, DISPLAY_SEQ, CREATED_BY)
    VALUES ('DEPT_HIERARCHY', 'MFG', 'Manufacturing', l_ops, 30, 'SEED');

    INSERT INTO VALUE_SET_VALUES (VALUE_SET_CODE, VALUE_CODE, VALUE_NAME, PARENT_VALUE_ID, DISPLAY_SEQ, CREATED_BY)
    VALUES ('DEPT_HIERARCHY', 'DIST', 'Distribution', l_ops, 40, 'SEED');

    INSERT INTO VALUE_SET_VALUES (VALUE_SET_CODE, VALUE_CODE, VALUE_NAME, DISPLAY_SEQ, CREATED_BY)
    VALUES ('COST_CENTER', 'CC1000', 'Corporate Overhead', 10, 'SEED');
    INSERT INTO VALUE_SET_VALUES (VALUE_SET_CODE, VALUE_CODE, VALUE_NAME, DISPLAY_SEQ, CREATED_BY)
    VALUES ('COST_CENTER', 'CC2000', 'Plant Operations', 20, 'SEED');
END;
/

-- ---------- Audit log sample ----------
INSERT INTO AUDIT_LOG (USER_ID, ROLE_CODE, ACTION, ENTITY_TYPE, ENTITY_KEY, SUMMARY, IP_ADDRESS, STATUS)
SELECT USER_ID, 'SYS_ADMIN', 'CREATE', 'lookup-type', 'EMP_STATUS',
       'Created lookup type EMP_STATUS', '10.20.30.40', 'success'
FROM USERS WHERE USERNAME = 'sarah.chen';

INSERT INTO AUDIT_LOG (USER_ID, ROLE_CODE, ACTION, ENTITY_TYPE, ENTITY_KEY, SUMMARY, IP_ADDRESS, STATUS)
SELECT USER_ID, 'HR_ADMIN', 'UPDATE', 'value-set', 'DEPT_HIERARCHY',
       'Updated department hierarchy values', '10.20.30.41', 'success'
FROM USERS WHERE USERNAME = 'michael.rodriguez';

COMMIT;
